services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    privileged: true
    network_mode: host
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    env_file:
      - ./common/env-config.txt
    volumes:
      - ./thelounge/config:/config
    ports:
      - 9000:9000
      # proxy servers
      # - 8080:8080
      # - 1000:1000
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    env_file:
    - ./common/env-config.txt
    - ./common/env-gluetun.txt
    ports:
      # gluetun
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      # jackett
      - 9117:9117
      # deluge
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp      
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - ./common/env-config.txt
      - ./common/env-swag.txt
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - ./common/env-config.txt
    volumes:
      - ./sonarr/data:/config
      - /media/usb1/TVShows:/tv
      - /media/usb1/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - ./common/env-config.txt
    volumes:
      - ./radarr/config:/config
      - /media/usb1/Movies:/movies
      - /media/usb1/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    env_file:
      - ./common/env-config.txt
      - ./common/env-jackett.txt
    volumes:
      - ./common/jacket/config:/config
      - /media/usb1/Downloads:/downloads
   # ports:
   #   - 9117:9117
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: "service:gluetun"
    env_file:
      - ./common/env-config.txt
      - ./common/env-deluge.txt
    volumes:
      - ./deluge/config:/config
      - /media/usb1/Downloads:/downloads
   # ports:
   #   - 8112:8112
   #   - 6881:6881
   #   - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - ./common/env-config.txt
      - ./common/env-jellyfin.txt
    volumes:
      - ./jellyfin/config:/config
      - /media/usb1/TVShows:/data/tvshows
      - /media/usb1/Movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
  
networks:
  default:
      external:
        name: valkyrie
